### ISSUE TITLE
页面缩放及窗口展开大小，影响页面多个按钮点击

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/zero2ckb-web#12]
os: win10
browser version: 版本 99.0.4844.51（正式版本） （64 位）
操作：

1. 浏览器处于最大化状态，页面显示正常；
2. 浏览器处于2/3宽度状态，页面调整，页面上缘测试链更新说明与语言选项元素重合，更新说明【ok】按钮及交易演示区【设置】按钮无法点击；（预期：浏览器窗口大小不影响页面功能）
3. 页面放大到150%，页面调整，页面上缘测试链更新说明与语言选项元素重合，更新说明【ok】按钮无法点击；（预期：网页缩放大小不影响页面功能）
![image](https://user-images.githubusercontent.com/18527271/159163386-2d08909b-d618-4589-8ed2-b2a41aa98853.png)

<img width="501" alt="image" src="https://user-images.githubusercontent.com/18527271/158361070-d996fd08-a13d-4ae3-b7ab-505f36148529.png">
![image](https://user-images.githubusercontent.com/18527271/159399642-7923cdf3-03fd-42d7-93af-9b81d7d878c9.png)

**Comment by BourneNeo** [comment]
浏览器处在放大状态

**Comment by RetricSu** [comment]
https://github.com/RetricSu/zero2ckb-web/pull/33
