### ISSUE TITLE
【第二步：动手实践-观察一条链】英文表述容易造成困扰，建议加一个“click"动作指示

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/zero2ckb-web#15]
建议改为"click and select..."
![image](https://user-images.githubusercontent.com/18527271/158499379-81b88367-de25-4da1-9b94-c2e599708ec1.png)

**Comment by RetricSu** [comment]
should be solved after deploying the fix https://github.com/RetricSu/zero2ckb-web/pull/32
