### ISSUE TITLE
【第一步：最小化的理论知识-怎么知道你的 Cell 属于你?】缺少shannon的内容，导致多处无法理解

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/zero2ckb-web#18]
![image](https://user-images.githubusercontent.com/18527271/158763400-d4b04286-f8fe-4eca-a291-2e6a37f43625.png)
![image](https://user-images.githubusercontent.com/18527271/158767287-ccb4e38f-6963-44d4-9126-ae8682275076.png)
![image](https://user-images.githubusercontent.com/18527271/158767962-fc5bed6c-1e8a-4242-8bdd-8e48091cd248.png)
![image](https://user-images.githubusercontent.com/18527271/158768470-d3750c62-6812-4772-b66c-01cc117b1710.png)

**Comment by RetricSu** [comment]
https://github.com/RetricSu/zero2ckb-web/pull/35
