### ISSUE TITLE
【第二步：动手实践-交易的 OUTPUT】“设置”窗口中，对内容格式有要求的输入框对输入内容无限制，导致非法输入有效

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/zero2ckb-web#19]
![image](https://user-images.githubusercontent.com/18527271/158922110-a46442d3-924f-47c3-8e3e-25d9ce4ff0f2.png)
![image](https://user-images.githubusercontent.com/18527271/158922140-a7d80681-a059-4af3-b0cf-f82555c2decc.png)
![image](https://user-images.githubusercontent.com/18527271/158923110-691ddca9-f19a-42e7-9659-2cdbbce15461.png)

**Comment by RetricSu** [comment]
should be solved after deploying the fix https://github.com/RetricSu/zero2ckb-web/commit/d6aabd9af1c415035736bc431ba90785a7963fea
