### ISSUE TITLE
【第二步：动手实践-交易的 OUTPUT】“设置”窗口中，非法数据成功输入，导致页面内容无法显示

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/zero2ckb-web#20]
步骤：
1、在生成交易演示区的output部分，设置->加一个新Cell->capacity输入框中输入一个负整数
2、点击”保存“，保存成功，无异常提示；
3、点击“保存退出”，成功，无异常提示，退出后页面内容显示不出。
![image](https://user-images.githubusercontent.com/18527271/158924150-695b6884-5339-401a-86e4-382c4c17c9c4.png)
![image](https://user-images.githubusercontent.com/18527271/158924557-f379739e-987d-4d7c-9da7-2d6f062a3702.png)
![image](https://user-images.githubusercontent.com/18527271/158924826-3c5a16da-9164-47b7-804a-08ee30446cf6.png)

**Comment by RetricSu** [comment]
should be solved after deploying the fix https://github.com/RetricSu/zero2ckb-web/pull/31/commits/d6aabd9af1c415035736bc431ba90785a7963fea
