### ISSUE TITLE
【动手实践-发送一笔交易-交易的INPUT,交易的OUTPUT】偶现演示区cell无法拖入输入框

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/zero2ckb-web#24]
偶现：演示区cell无法拖入输入框，刷新页面后恢复
触发条件：未知

https://user-images.githubusercontent.com/18527271/159200225-f56b5fba-8bde-4826-9e0e-320f7563a214.mp4

**Comment by RetricSu** [comment]
what is your system info and browser version? 

can not reproduce on my M1 mac, delay in addressing

**Comment by BourneNeo** [comment]
偶现，暂未复现，关闭。
