### ISSUE TITLE
【第二步：动手实践-构造交易-生成待签名的 message】raw_tx生成tx_hash成功，生成message失败，无错误提示

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/zero2ckb-web#28]
操作：
1、在交易模板中填入以下内容：
{
  "version": "0x0",
  "header_deps": [],
  "cell_deps": [
    {
      "out_point": {
        "tx_hash": "0x4f1097802dc6fe19b942f1c2e8e52d564ee35899e4aef308101c86c49bc1f471",
        "index": "0x0"
      },
      "dep_type": "dep_group"
    }
  ],
  "inputs": [
    {
      "previous_output": {
        "tx_hash": "0xbbff9e98d6989678484a32c3bfeac66840ca28c5b927031b938153bc4ab1e20a",
        "index": "0x0"
      },
      "since": "0x0"
    },
    {
      "previous_output": {
        "tx_hash": "0xd0317b3e2e24ce14f806d3fb46f8d40f593d445e3dca0dbe6effde59e8275b29",
        "index": "0x0"
      },
      "since": "0x0"
    }
  ],
  "outputs": [
    {
      "capacity": "0x2e90edd000",
      "lock": {
        "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
        "hash_type": "type",
        "args": "0x43d509d97f26007a285f39241cffcd411157196c"
      }
    }
  ],
  "outputs_data": [
    "0x"
  ],
  "witnesses": [
    "0x",
    "0x"
  ]
}
2、生成tx_hash，成功；
3、生成message，失败，无提示。（预期：失败，提示错误）
![image](https://user-images.githubusercontent.com/18527271/159449577-0802a68a-6f4c-41e5-ab27-bab611852abb.png)

**Comment by RetricSu** [comment]
should be solved after deploying the fix https://github.com/RetricSu/zero2ckb-server/pull/8/commits/55d84ea382e855ce96379476c92e205ab4e38c0e

**Comment by tarvos21** [comment]
@RetricSu 您好，请问下，我昨天使用zero2ckb，遇到同样的问题，可以生成tx_hash，但生成message时，右上角出现报错，没找到live cell？

关于这个地方，有两个问题：

1. Inputs里的 tx_hash 和 index 怎么看是有效的？
2. Outputs里的几个字段需要填入什么？
