### ISSUE TITLE
【第二步：动手实践-观察一条链】后台k8s node升级，ckb miner重启后，部分账户获取信息出现异常，但错误信息无内容

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/zero2ckb-web#29]
操作：1、在“钱包对应的live cell”窗口，选择钱包2，查看返回结果
预期：钱包有对应的live cell，则返回live cell及相应的交易
实际: 
1、返回信息有交易但看不到cell,无错误提示；
![image](https://user-images.githubusercontent.com/18527271/159457824-f08fde19-54c3-4f51-b9ac-9b2fbfee3696.png)
2、返回信息有交易但看不到cell,有错误提示，但内容空白；
![image](https://user-images.githubusercontent.com/18527271/159458165-f04e598c-97c8-4f46-a82d-92feade3d5b9.png)

3、返回cell及交易，无错误提示，但多次返回的交易数量不一样
![image](https://user-images.githubusercontent.com/18527271/159458384-5e9c40dc-350b-4507-9464-e517e9a49e9b.png)

**Comment by RetricSu** [comment]
1. possible, no live cells for consuming all the cells in transactions.
2. should have err msg display after the [code refactor](https://github.com/RetricSu/zero2ckb-web/pull/30)
3. can not reproduce the err, pass for now
