### ISSUE TITLE
more clear error info for even-length Hexadecimal

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/zero2ckb-web#38]
![image](https://user-images.githubusercontent.com/18527271/160983016-a754f5b5-f5da-419c-beed-744543417563.png)

**Comment by RetricSu** [comment]
please use `0x011111`, Hexadecimal input string must have an even length

**Comment by BourneNeo** [comment]
> please use `0x011111`, Hexadecimal input string must have an even length

but one can use the box convert decimal number like '273' to hex number '0x111', but not the other way around, it's odd, isn't it?

**Comment by RetricSu** [comment]
> > please use `0x011111`, Hexadecimal input string must have an even length
> 
> but one can use the box convert decimal number like '273' to hex number '0x111', but not the other way around, it's odd, isn't it?

you are right, the validate rule should be different for HexNumber and HexString, the even length requirement should apply for HexString not HexNumber, fix pr: https://github.com/RetricSu/zero2ckb-web/pull/42

**Comment by RetricSu** [comment]
should be fixed now. feel free to reopen it if you still encounter trouble
