### ISSUE TITLE
【第二步：动手实践-观察一条链】较长的交易内容在浏览器自然状态下显示不全

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/zero2ckb-web#40]
![image](https://user-images.githubusercontent.com/18527271/160989435-cd6477c5-5c78-47f7-950d-9c9eec5ee62f.png)

**Comment by RetricSu** [comment]
how can I reproduce this issue? can you provide some steps?

**Comment by BourneNeo** [comment]
> how can I reproduce this issue? can you provide some steps?

you can just choose this tx and check its detail:
![image](https://user-images.githubusercontent.com/18527271/161183038-c7ea0903-db27-4b1c-a8d1-875794715a82.png)

**Comment by RetricSu** [comment]
- https://github.com/RetricSu/zero2ckb-web/pull/48
