### ISSUE TITLE
Multiple input transaction failure

### ISSUE THREAD

**Issue by ShookLyngs** [RetricSu/zero2ckb-web#52]
When I select multiple inputs in a transaction, the transaction failed with `ValidationFailure(-31)`.  
However, when I only select a single cell as the input, the transaction completes without error.

Here's an image of the error:
![image](https://user-images.githubusercontent.com/44739165/177243124-ed050984-263c-4825-b5c2-ca95d31f89ec.png)

**Comment by RetricSu** [comment]
hi, I just tried with two inputs from one account to generate one output, it works:

```sh
{
  "version": "0x0",
  "header_deps": [],
  "cell_deps": [
    {
      "out_point": {
        "tx_hash": "0x4f1097802dc6fe19b942f1c2e8e52d564ee35899e4aef308101c86c49bc1f471",
        "index": "0x0"
      },
      "dep_type": "dep_group"
    }
  ],
  "inputs": [
    {
      "previous_output": {
        "tx_hash": "0x47a3e1da3b8c223b2feab2b7ae1b3db4ad8ef06e54642e377a2ca049707cb278",
        "index": "0x0"
      },
      "since": "0x0"
    },
    {
      "previous_output": {
        "tx_hash": "0x3a28e439d66a2cb2486d8cc40eda04fef086107ccf201a8e27433803aadb7002",
        "index": "0x0"
      },
      "since": "0x0"
    }
  ],
  "outputs": [
    {
      "capacity": "0x5d21dba000",
      "lock": {
        "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
        "hash_type": "type",
        "args": "0x00"
      }
    }
  ],
  "outputs_data": [
    "0x"
  ],
  "witnesses": [
    "0x55000000100000005500000055000000410000001cac51e29588bade961195bdaa15b370cd01b1025618d1d4b68bc7f2b1d2925d1761af7ad9933da98fb630f4c3af2bbc9e10f97bbe19de60d7a11a5e87edc63f01",
    "0x"
  ]
}
```

are your two inputs from two different accounts? Can you paste the fail transaction content?

**Comment by ShookLyngs** [comment]
> are your two inputs from two different accounts? Can you paste the fail transaction content?

No, both inputs belong to account 1.  
But by watching your example I have just figure out the real cause of the error:

In my transaction, I didn't know that the length of witnesses should equal to the length of inputs, so I just put a single witness in the withnesses list. But based on your example, actually there should be `two` of them, one has value and one left empty.
